version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  ts-node-docker:
    volumes:
      - F:\dev\mywork\backend-ts:/app:ro
      - /app/node_modules
    expose:
      - "4050"
    ports:
      - "4050:4000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    command: npm run dev
